// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equipe.proto

// Protobuf Java Version: 3.25.1
package grpcjavafx;

/**
 * Protobuf type {@code EquipeResponse}
 */
public final class EquipeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EquipeResponse)
    EquipeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EquipeResponse.newBuilder() to construct.
  private EquipeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EquipeResponse() {
    equipe_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EquipeResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpcjavafx.EquipeProto.internal_static_EquipeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpcjavafx.EquipeProto.internal_static_EquipeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpcjavafx.EquipeResponse.class, grpcjavafx.EquipeResponse.Builder.class);
  }

  public static final int EQUIPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList equipe_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string equipe = 1;</code>
   * @return A list containing the equipe.
   */
  public com.google.protobuf.ProtocolStringList
      getEquipeList() {
    return equipe_;
  }
  /**
   * <code>repeated string equipe = 1;</code>
   * @return The count of equipe.
   */
  public int getEquipeCount() {
    return equipe_.size();
  }
  /**
   * <code>repeated string equipe = 1;</code>
   * @param index The index of the element to return.
   * @return The equipe at the given index.
   */
  public java.lang.String getEquipe(int index) {
    return equipe_.get(index);
  }
  /**
   * <code>repeated string equipe = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the equipe at the given index.
   */
  public com.google.protobuf.ByteString
      getEquipeBytes(int index) {
    return equipe_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < equipe_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipe_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < equipe_.size(); i++) {
        dataSize += computeStringSizeNoTag(equipe_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEquipeList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpcjavafx.EquipeResponse)) {
      return super.equals(obj);
    }
    grpcjavafx.EquipeResponse other = (grpcjavafx.EquipeResponse) obj;

    if (!getEquipeList()
        .equals(other.getEquipeList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEquipeCount() > 0) {
      hash = (37 * hash) + EQUIPE_FIELD_NUMBER;
      hash = (53 * hash) + getEquipeList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpcjavafx.EquipeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcjavafx.EquipeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpcjavafx.EquipeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpcjavafx.EquipeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpcjavafx.EquipeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpcjavafx.EquipeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpcjavafx.EquipeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EquipeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EquipeResponse)
      grpcjavafx.EquipeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcjavafx.EquipeProto.internal_static_EquipeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcjavafx.EquipeProto.internal_static_EquipeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpcjavafx.EquipeResponse.class, grpcjavafx.EquipeResponse.Builder.class);
    }

    // Construct using grpcjavafx.EquipeResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      equipe_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpcjavafx.EquipeProto.internal_static_EquipeResponse_descriptor;
    }

    @java.lang.Override
    public grpcjavafx.EquipeResponse getDefaultInstanceForType() {
      return grpcjavafx.EquipeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpcjavafx.EquipeResponse build() {
      grpcjavafx.EquipeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpcjavafx.EquipeResponse buildPartial() {
      grpcjavafx.EquipeResponse result = new grpcjavafx.EquipeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpcjavafx.EquipeResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        equipe_.makeImmutable();
        result.equipe_ = equipe_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpcjavafx.EquipeResponse) {
        return mergeFrom((grpcjavafx.EquipeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpcjavafx.EquipeResponse other) {
      if (other == grpcjavafx.EquipeResponse.getDefaultInstance()) return this;
      if (!other.equipe_.isEmpty()) {
        if (equipe_.isEmpty()) {
          equipe_ = other.equipe_;
          bitField0_ |= 0x00000001;
        } else {
          ensureEquipeIsMutable();
          equipe_.addAll(other.equipe_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureEquipeIsMutable();
              equipe_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList equipe_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureEquipeIsMutable() {
      if (!equipe_.isModifiable()) {
        equipe_ = new com.google.protobuf.LazyStringArrayList(equipe_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @return A list containing the equipe.
     */
    public com.google.protobuf.ProtocolStringList
        getEquipeList() {
      equipe_.makeImmutable();
      return equipe_;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @return The count of equipe.
     */
    public int getEquipeCount() {
      return equipe_.size();
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param index The index of the element to return.
     * @return The equipe at the given index.
     */
    public java.lang.String getEquipe(int index) {
      return equipe_.get(index);
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the equipe at the given index.
     */
    public com.google.protobuf.ByteString
        getEquipeBytes(int index) {
      return equipe_.getByteString(index);
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param index The index to set the value at.
     * @param value The equipe to set.
     * @return This builder for chaining.
     */
    public Builder setEquipe(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEquipeIsMutable();
      equipe_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param value The equipe to add.
     * @return This builder for chaining.
     */
    public Builder addEquipe(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEquipeIsMutable();
      equipe_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param values The equipe to add.
     * @return This builder for chaining.
     */
    public Builder addAllEquipe(
        java.lang.Iterable<java.lang.String> values) {
      ensureEquipeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, equipe_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEquipe() {
      equipe_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string equipe = 1;</code>
     * @param value The bytes of the equipe to add.
     * @return This builder for chaining.
     */
    public Builder addEquipeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEquipeIsMutable();
      equipe_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EquipeResponse)
  }

  // @@protoc_insertion_point(class_scope:EquipeResponse)
  private static final grpcjavafx.EquipeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpcjavafx.EquipeResponse();
  }

  public static grpcjavafx.EquipeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EquipeResponse>
      PARSER = new com.google.protobuf.AbstractParser<EquipeResponse>() {
    @java.lang.Override
    public EquipeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EquipeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EquipeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpcjavafx.EquipeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

