// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equipe.proto

// Protobuf Java Version: 3.25.1
package grpcjavafx;

public final class EquipeProto {
  private EquipeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EquipeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EquipeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EquipeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EquipeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014equipe.proto\"\033\n\rEquipeRequest\022\n\n\002id\030\001 " +
      "\001(\005\" \n\016EquipeResponse\022\016\n\006equipe\030\001 \003(\t2A\n" +
      "\rEquipeService\0220\n\rgetEquipeInfo\022\016.Equipe" +
      "Request\032\017.EquipeResponseB\033\n\ngrpcjavafxB\013" +
      "EquipeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EquipeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EquipeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EquipeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_EquipeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EquipeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EquipeResponse_descriptor,
        new java.lang.String[] { "Equipe", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
