// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equipe.proto

// Protobuf Java Version: 3.25.1
package grpcjavafx;

public interface EquipeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EquipeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string equipe = 1;</code>
   * @return A list containing the equipe.
   */
  java.util.List<java.lang.String>
      getEquipeList();
  /**
   * <code>repeated string equipe = 1;</code>
   * @return The count of equipe.
   */
  int getEquipeCount();
  /**
   * <code>repeated string equipe = 1;</code>
   * @param index The index of the element to return.
   * @return The equipe at the given index.
   */
  java.lang.String getEquipe(int index);
  /**
   * <code>repeated string equipe = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the equipe at the given index.
   */
  com.google.protobuf.ByteString
      getEquipeBytes(int index);
}
