// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: equipe.proto

// Protobuf Java Version: 3.25.1
package grpcjavafx;

public interface EquipeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EquipeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
