// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

/**
 * Protobuf type {@code javafx.agendamento.Agendamento}
 */
public final class Agendamento extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:javafx.agendamento.Agendamento)
    AgendamentoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Agendamento.newBuilder() to construct.
  private Agendamento(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Agendamento() {
    tipo_ = "";
    data_ = "";
    hora_ = "";
    status_ = "";
    nomeCliente_ = "";
    nomeAnimal_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Agendamento();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_Agendamento_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_Agendamento_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafx.agendamento.Agendamento.class, javafx.agendamento.Agendamento.Builder.class);
  }

  public static final int ID_AGENDAMENTO_FIELD_NUMBER = 1;
  private int idAgendamento_ = 0;
  /**
   * <code>int32 id_agendamento = 1;</code>
   * @return The idAgendamento.
   */
  @java.lang.Override
  public int getIdAgendamento() {
    return idAgendamento_;
  }

  public static final int ID_CLIENTE_FIELD_NUMBER = 2;
  private int idCliente_ = 0;
  /**
   * <code>int32 id_cliente = 2;</code>
   * @return The idCliente.
   */
  @java.lang.Override
  public int getIdCliente() {
    return idCliente_;
  }

  public static final int ID_ANIMAL_FIELD_NUMBER = 3;
  private int idAnimal_ = 0;
  /**
   * <code>int32 id_animal = 3;</code>
   * @return The idAnimal.
   */
  @java.lang.Override
  public int getIdAnimal() {
    return idAnimal_;
  }

  public static final int TIPO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tipo_ = "";
  /**
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  @java.lang.Override
  public java.lang.String getTipo() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tipo_ = s;
      return s;
    }
  }
  /**
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipoBytes() {
    java.lang.Object ref = tipo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tipo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object data_ = "";
  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HORA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hora_ = "";
  /**
   * <code>string hora = 6;</code>
   * @return The hora.
   */
  @java.lang.Override
  public java.lang.String getHora() {
    java.lang.Object ref = hora_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hora_ = s;
      return s;
    }
  }
  /**
   * <code>string hora = 6;</code>
   * @return The bytes for hora.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHoraBytes() {
    java.lang.Object ref = hora_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hora_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 7;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 7;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_CLIENTE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nomeCliente_ = "";
  /**
   * <code>string nome_cliente = 8;</code>
   * @return The nomeCliente.
   */
  @java.lang.Override
  public java.lang.String getNomeCliente() {
    java.lang.Object ref = nomeCliente_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeCliente_ = s;
      return s;
    }
  }
  /**
   * <code>string nome_cliente = 8;</code>
   * @return The bytes for nomeCliente.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeClienteBytes() {
    java.lang.Object ref = nomeCliente_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeCliente_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_ANIMAL_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nomeAnimal_ = "";
  /**
   * <code>string nome_animal = 9;</code>
   * @return The nomeAnimal.
   */
  @java.lang.Override
  public java.lang.String getNomeAnimal() {
    java.lang.Object ref = nomeAnimal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeAnimal_ = s;
      return s;
    }
  }
  /**
   * <code>string nome_animal = 9;</code>
   * @return The bytes for nomeAnimal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeAnimalBytes() {
    java.lang.Object ref = nomeAnimal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeAnimal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idAgendamento_ != 0) {
      output.writeInt32(1, idAgendamento_);
    }
    if (idCliente_ != 0) {
      output.writeInt32(2, idCliente_);
    }
    if (idAnimal_ != 0) {
      output.writeInt32(3, idAnimal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tipo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hora_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, hora_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nomeCliente_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nomeCliente_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nomeAnimal_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, nomeAnimal_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idAgendamento_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idAgendamento_);
    }
    if (idCliente_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, idCliente_);
    }
    if (idAnimal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, idAnimal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tipo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tipo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hora_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, hora_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nomeCliente_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nomeCliente_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nomeAnimal_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, nomeAnimal_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafx.agendamento.Agendamento)) {
      return super.equals(obj);
    }
    javafx.agendamento.Agendamento other = (javafx.agendamento.Agendamento) obj;

    if (getIdAgendamento()
        != other.getIdAgendamento()) return false;
    if (getIdCliente()
        != other.getIdCliente()) return false;
    if (getIdAnimal()
        != other.getIdAnimal()) return false;
    if (!getTipo()
        .equals(other.getTipo())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (!getHora()
        .equals(other.getHora())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getNomeCliente()
        .equals(other.getNomeCliente())) return false;
    if (!getNomeAnimal()
        .equals(other.getNomeAnimal())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_AGENDAMENTO_FIELD_NUMBER;
    hash = (53 * hash) + getIdAgendamento();
    hash = (37 * hash) + ID_CLIENTE_FIELD_NUMBER;
    hash = (53 * hash) + getIdCliente();
    hash = (37 * hash) + ID_ANIMAL_FIELD_NUMBER;
    hash = (53 * hash) + getIdAnimal();
    hash = (37 * hash) + TIPO_FIELD_NUMBER;
    hash = (53 * hash) + getTipo().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + HORA_FIELD_NUMBER;
    hash = (53 * hash) + getHora().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + NOME_CLIENTE_FIELD_NUMBER;
    hash = (53 * hash) + getNomeCliente().hashCode();
    hash = (37 * hash) + NOME_ANIMAL_FIELD_NUMBER;
    hash = (53 * hash) + getNomeAnimal().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafx.agendamento.Agendamento parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.Agendamento parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.Agendamento parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static javafx.agendamento.Agendamento parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static javafx.agendamento.Agendamento parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.Agendamento parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafx.agendamento.Agendamento prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code javafx.agendamento.Agendamento}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:javafx.agendamento.Agendamento)
      javafx.agendamento.AgendamentoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_Agendamento_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_Agendamento_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafx.agendamento.Agendamento.class, javafx.agendamento.Agendamento.Builder.class);
    }

    // Construct using javafx.agendamento.Agendamento.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idAgendamento_ = 0;
      idCliente_ = 0;
      idAnimal_ = 0;
      tipo_ = "";
      data_ = "";
      hora_ = "";
      status_ = "";
      nomeCliente_ = "";
      nomeAnimal_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_Agendamento_descriptor;
    }

    @java.lang.Override
    public javafx.agendamento.Agendamento getDefaultInstanceForType() {
      return javafx.agendamento.Agendamento.getDefaultInstance();
    }

    @java.lang.Override
    public javafx.agendamento.Agendamento build() {
      javafx.agendamento.Agendamento result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public javafx.agendamento.Agendamento buildPartial() {
      javafx.agendamento.Agendamento result = new javafx.agendamento.Agendamento(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(javafx.agendamento.Agendamento result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idAgendamento_ = idAgendamento_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idCliente_ = idCliente_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idAnimal_ = idAnimal_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tipo_ = tipo_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.data_ = data_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.hora_ = hora_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.nomeCliente_ = nomeCliente_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.nomeAnimal_ = nomeAnimal_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafx.agendamento.Agendamento) {
        return mergeFrom((javafx.agendamento.Agendamento)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafx.agendamento.Agendamento other) {
      if (other == javafx.agendamento.Agendamento.getDefaultInstance()) return this;
      if (other.getIdAgendamento() != 0) {
        setIdAgendamento(other.getIdAgendamento());
      }
      if (other.getIdCliente() != 0) {
        setIdCliente(other.getIdCliente());
      }
      if (other.getIdAnimal() != 0) {
        setIdAnimal(other.getIdAnimal());
      }
      if (!other.getTipo().isEmpty()) {
        tipo_ = other.tipo_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getHora().isEmpty()) {
        hora_ = other.hora_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getNomeCliente().isEmpty()) {
        nomeCliente_ = other.nomeCliente_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getNomeAnimal().isEmpty()) {
        nomeAnimal_ = other.nomeAnimal_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              idAgendamento_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              idCliente_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              idAnimal_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              tipo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              data_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              hora_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              nomeCliente_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              nomeAnimal_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int idAgendamento_ ;
    /**
     * <code>int32 id_agendamento = 1;</code>
     * @return The idAgendamento.
     */
    @java.lang.Override
    public int getIdAgendamento() {
      return idAgendamento_;
    }
    /**
     * <code>int32 id_agendamento = 1;</code>
     * @param value The idAgendamento to set.
     * @return This builder for chaining.
     */
    public Builder setIdAgendamento(int value) {

      idAgendamento_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id_agendamento = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdAgendamento() {
      bitField0_ = (bitField0_ & ~0x00000001);
      idAgendamento_ = 0;
      onChanged();
      return this;
    }

    private int idCliente_ ;
    /**
     * <code>int32 id_cliente = 2;</code>
     * @return The idCliente.
     */
    @java.lang.Override
    public int getIdCliente() {
      return idCliente_;
    }
    /**
     * <code>int32 id_cliente = 2;</code>
     * @param value The idCliente to set.
     * @return This builder for chaining.
     */
    public Builder setIdCliente(int value) {

      idCliente_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id_cliente = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdCliente() {
      bitField0_ = (bitField0_ & ~0x00000002);
      idCliente_ = 0;
      onChanged();
      return this;
    }

    private int idAnimal_ ;
    /**
     * <code>int32 id_animal = 3;</code>
     * @return The idAnimal.
     */
    @java.lang.Override
    public int getIdAnimal() {
      return idAnimal_;
    }
    /**
     * <code>int32 id_animal = 3;</code>
     * @param value The idAnimal to set.
     * @return This builder for chaining.
     */
    public Builder setIdAnimal(int value) {

      idAnimal_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id_animal = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdAnimal() {
      bitField0_ = (bitField0_ & ~0x00000004);
      idAnimal_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tipo_ = "";
    /**
     * <code>string tipo = 4;</code>
     * @return The tipo.
     */
    public java.lang.String getTipo() {
      java.lang.Object ref = tipo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tipo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tipo = 4;</code>
     * @return The bytes for tipo.
     */
    public com.google.protobuf.ByteString
        getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tipo = 4;</code>
     * @param value The tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tipo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTipo() {
      tipo_ = getDefaultInstance().getTipo();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string tipo = 4;</code>
     * @param value The bytes for tipo to set.
     * @return This builder for chaining.
     */
    public Builder setTipoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tipo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      data_ = getDefaultInstance().getData();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string data = 5;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      data_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object hora_ = "";
    /**
     * <code>string hora = 6;</code>
     * @return The hora.
     */
    public java.lang.String getHora() {
      java.lang.Object ref = hora_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hora_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hora = 6;</code>
     * @return The bytes for hora.
     */
    public com.google.protobuf.ByteString
        getHoraBytes() {
      java.lang.Object ref = hora_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hora_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hora = 6;</code>
     * @param value The hora to set.
     * @return This builder for chaining.
     */
    public Builder setHora(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hora_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    
    /**
     * <code>string hora = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHora() {
      hora_ = getDefaultInstance().getHora();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string hora = 6;</code>
     * @param value The bytes for hora to set.
     * @return This builder for chaining.
     */
    public Builder setHoraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hora_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    
    /**
     * <code>string status = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 7;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object nomeCliente_ = "";
    /**
     * <code>string nome_cliente = 8;</code>
     * @return The nomeCliente.
     */
    public java.lang.String getNomeCliente() {
      java.lang.Object ref = nomeCliente_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeCliente_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nome_cliente = 8;</code>
     * @return The bytes for nomeCliente.
     */
    public com.google.protobuf.ByteString
        getNomeClienteBytes() {
      java.lang.Object ref = nomeCliente_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeCliente_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
        
        
        
    /**
     * <code>string nome_cliente = 8;</code>
     * @param value The nomeCliente to set.
     * @return This builder for chaining.
     */
    public Builder setNomeCliente(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nomeCliente_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string nome_cliente = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNomeCliente() {
      nomeCliente_ = getDefaultInstance().getNomeCliente();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string nome_cliente = 8;</code>
     * @param value The bytes for nomeCliente to set.
     * @return This builder for chaining.
     */
    public Builder setNomeClienteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nomeCliente_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object nomeAnimal_ = "";
    /**
     * <code>string nome_animal = 9;</code>
     * @return The nomeAnimal.
     */
    public java.lang.String getNomeAnimal() {
      java.lang.Object ref = nomeAnimal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeAnimal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nome_animal = 9;</code>
     * @return The bytes for nomeAnimal.
     */
    public com.google.protobuf.ByteString
        getNomeAnimalBytes() {
      java.lang.Object ref = nomeAnimal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeAnimal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nome_animal = 9;</code>
     * @param value The nomeAnimal to set.
     * @return This builder for chaining.
     */
    public Builder setNomeAnimal(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nomeAnimal_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string nome_animal = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNomeAnimal() {
      nomeAnimal_ = getDefaultInstance().getNomeAnimal();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string nome_animal = 9;</code>
     * @param value The bytes for nomeAnimal to set.
     * @return This builder for chaining.
     */
    public Builder setNomeAnimalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nomeAnimal_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:javafx.agendamento.Agendamento)
  }

  // @@protoc_insertion_point(class_scope:javafx.agendamento.Agendamento)
  private static final javafx.agendamento.Agendamento DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafx.agendamento.Agendamento();
  }

  public static javafx.agendamento.Agendamento getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Agendamento>
      PARSER = new com.google.protobuf.AbstractParser<Agendamento>() {
    @java.lang.Override
    public Agendamento parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Agendamento> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Agendamento> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public javafx.agendamento.Agendamento getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

