// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public final class AgendaProto {
  private AgendaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javafx_agendamento_GetAgendamentosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javafx_agendamento_GetAgendamentosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javafx_agendamento_GetAgendamentosResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javafx_agendamento_Agendamento_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javafx_agendamento_Agendamento_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014agenda.proto\022\022javafx.agendamento\"\030\n\026Ge" +
      "tAgendamentosRequest\"P\n\027GetAgendamentosR" +
      "esponse\0225\n\014agendamentos\030\001 \003(\0132\037.javafx.a" +
      "gendamento.Agendamento\"N\n!AtualizarStatu" +
      "sAgendamentoRequest\022\025\n\ridAgendamento\030\001 \001" +
      "(\005\022\022\n\nnovoStatus\030\002 \001(\t\"5\n\"AtualizarStatu" +
      "sAgendamentoResponse\022\017\n\007sucesso\030\001 \001(\010\"\261\001" +
      "\n\013Agendamento\022\026\n\016id_agendamento\030\001 \001(\005\022\022\n" +
      "\nid_cliente\030\002 \001(\005\022\021\n\tid_animal\030\003 \001(\005\022\014\n\004" +
      "tipo\030\004 \001(\t\022\014\n\004data\030\005 \001(\t\022\014\n\004hora\030\006 \001(\t\022\016" +
      "\n\006status\030\007 \001(\t\022\024\n\014nome_cliente\030\010 \001(\t\022\023\n\013" +
      "nome_animal\030\t \001(\t2\211\002\n\rAgendaService\022j\n\017G" +
      "etAgendamentos\022*.javafx.agendamento.GetA" +
      "gendamentosRequest\032+.javafx.agendamento." +
      "GetAgendamentosResponse\022\213\001\n\032AtualizarSta" +
      "tusAgendamento\0225.javafx.agendamento.Atua" +
      "lizarStatusAgendamentoRequest\0326.javafx.a" +
      "gendamento.AtualizarStatusAgendamentoRes" +
      "ponseB#\n\022javafx.agendamentoB\013AgendaProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_javafx_agendamento_GetAgendamentosRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_javafx_agendamento_GetAgendamentosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javafx_agendamento_GetAgendamentosRequest_descriptor,
        new java.lang.String[] { });
    internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_javafx_agendamento_GetAgendamentosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor,
        new java.lang.String[] { "Agendamentos", });
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor,
        new java.lang.String[] { "IdAgendamento", "NovoStatus", });
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor,
        new java.lang.String[] { "Sucesso", });
    internal_static_javafx_agendamento_Agendamento_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_javafx_agendamento_Agendamento_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javafx_agendamento_Agendamento_descriptor,
        new java.lang.String[] { "IdAgendamento", "IdCliente", "IdAnimal", "Tipo", "Data", "Hora", "Status", "NomeCliente", "NomeAnimal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
