// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public interface AgendamentoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javafx.agendamento.Agendamento)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id_agendamento = 1;</code>
   * @return The idAgendamento.
   */
  int getIdAgendamento();

  /**
   * <code>int32 id_cliente = 2;</code>
   * @return The idCliente.
   */
  int getIdCliente();

  /**
   * <code>int32 id_animal = 3;</code>
   * @return The idAnimal.
   */
  int getIdAnimal();

  /**
   * <code>string tipo = 4;</code>
   * @return The tipo.
   */
  java.lang.String getTipo();
  /**
   * <code>string tipo = 4;</code>
   * @return The bytes for tipo.
   */
  com.google.protobuf.ByteString
      getTipoBytes();

  /**
   * <code>string data = 5;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 5;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <code>string hora = 6;</code>
   * @return The hora.
   */
  java.lang.String getHora();
  /**
   * <code>string hora = 6;</code>
   * @return The bytes for hora.
   */
  com.google.protobuf.ByteString
      getHoraBytes();

  /**
   * <code>string status = 7;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 7;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string nome_cliente = 8;</code>
   * @return The nomeCliente.
   */
  java.lang.String getNomeCliente();
  /**
   * <code>string nome_cliente = 8;</code>
   * @return The bytes for nomeCliente.
   */
  com.google.protobuf.ByteString
      getNomeClienteBytes();

  /**
   * <code>string nome_animal = 9;</code>
   * @return The nomeAnimal.
   */
  java.lang.String getNomeAnimal();
  /**
   * <code>string nome_animal = 9;</code>
   * @return The bytes for nomeAnimal.
   */
  com.google.protobuf.ByteString
      getNomeAnimalBytes();
}
