// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public interface AtualizarStatusAgendamentoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javafx.agendamento.AtualizarStatusAgendamentoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool sucesso = 1;</code>
   * @return The sucesso.
   */
  boolean getSucesso();
}
