// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public interface AtualizarStatusAgendamentoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javafx.agendamento.AtualizarStatusAgendamentoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 idAgendamento = 1;</code>
   * @return The idAgendamento.
   */
  int getIdAgendamento();

  /**
   * <code>string novoStatus = 2;</code>
   * @return The novoStatus.
   */
  java.lang.String getNovoStatus();
  /**
   * <code>string novoStatus = 2;</code>
   * @return The bytes for novoStatus.
   */
  com.google.protobuf.ByteString
      getNovoStatusBytes();
}
