// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

/**
 * Protobuf type {@code javafx.agendamento.AtualizarStatusAgendamentoRequest}
 */
public final class AtualizarStatusAgendamentoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:javafx.agendamento.AtualizarStatusAgendamentoRequest)
    AtualizarStatusAgendamentoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AtualizarStatusAgendamentoRequest.newBuilder() to construct.
  private AtualizarStatusAgendamentoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AtualizarStatusAgendamentoRequest() {
    novoStatus_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AtualizarStatusAgendamentoRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafx.agendamento.AtualizarStatusAgendamentoRequest.class, javafx.agendamento.AtualizarStatusAgendamentoRequest.Builder.class);
  }

  public static final int IDAGENDAMENTO_FIELD_NUMBER = 1;
  private int idAgendamento_ = 0;
  /**
   * <code>int32 idAgendamento = 1;</code>
   * @return The idAgendamento.
   */
  @java.lang.Override
  public int getIdAgendamento() {
    return idAgendamento_;
  }

  public static final int NOVOSTATUS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object novoStatus_ = "";
  /**
   * <code>string novoStatus = 2;</code>
   * @return The novoStatus.
   */
  @java.lang.Override
  public java.lang.String getNovoStatus() {
    java.lang.Object ref = novoStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      novoStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string novoStatus = 2;</code>
   * @return The bytes for novoStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNovoStatusBytes() {
    java.lang.Object ref = novoStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      novoStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idAgendamento_ != 0) {
      output.writeInt32(1, idAgendamento_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(novoStatus_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, novoStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idAgendamento_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, idAgendamento_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(novoStatus_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, novoStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafx.agendamento.AtualizarStatusAgendamentoRequest)) {
      return super.equals(obj);
    }
    javafx.agendamento.AtualizarStatusAgendamentoRequest other = (javafx.agendamento.AtualizarStatusAgendamentoRequest) obj;

    if (getIdAgendamento()
        != other.getIdAgendamento()) return false;
    if (!getNovoStatus()
        .equals(other.getNovoStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IDAGENDAMENTO_FIELD_NUMBER;
    hash = (53 * hash) + getIdAgendamento();
    hash = (37 * hash) + NOVOSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getNovoStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafx.agendamento.AtualizarStatusAgendamentoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code javafx.agendamento.AtualizarStatusAgendamentoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:javafx.agendamento.AtualizarStatusAgendamentoRequest)
      javafx.agendamento.AtualizarStatusAgendamentoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafx.agendamento.AtualizarStatusAgendamentoRequest.class, javafx.agendamento.AtualizarStatusAgendamentoRequest.Builder.class);
    }

    // Construct using javafx.agendamento.AtualizarStatusAgendamentoRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idAgendamento_ = 0;
      novoStatus_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoRequest_descriptor;
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoRequest getDefaultInstanceForType() {
      return javafx.agendamento.AtualizarStatusAgendamentoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoRequest build() {
      javafx.agendamento.AtualizarStatusAgendamentoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoRequest buildPartial() {
      javafx.agendamento.AtualizarStatusAgendamentoRequest result = new javafx.agendamento.AtualizarStatusAgendamentoRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(javafx.agendamento.AtualizarStatusAgendamentoRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idAgendamento_ = idAgendamento_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.novoStatus_ = novoStatus_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafx.agendamento.AtualizarStatusAgendamentoRequest) {
        return mergeFrom((javafx.agendamento.AtualizarStatusAgendamentoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafx.agendamento.AtualizarStatusAgendamentoRequest other) {
      if (other == javafx.agendamento.AtualizarStatusAgendamentoRequest.getDefaultInstance()) return this;
      if (other.getIdAgendamento() != 0) {
        setIdAgendamento(other.getIdAgendamento());
      }
      if (!other.getNovoStatus().isEmpty()) {
        novoStatus_ = other.novoStatus_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              idAgendamento_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              novoStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int idAgendamento_ ;
    /**
     * <code>int32 idAgendamento = 1;</code>
     * @return The idAgendamento.
     */
    @java.lang.Override
    public int getIdAgendamento() {
      return idAgendamento_;
    }
    /**
     * <code>int32 idAgendamento = 1;</code>
     * @param value The idAgendamento to set.
     * @return This builder for chaining.
     */
    public Builder setIdAgendamento(int value) {

      idAgendamento_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 idAgendamento = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdAgendamento() {
      bitField0_ = (bitField0_ & ~0x00000001);
      idAgendamento_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object novoStatus_ = "";
    /**
     * <code>string novoStatus = 2;</code>
     * @return The novoStatus.
     */
    public java.lang.String getNovoStatus() {
      java.lang.Object ref = novoStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        novoStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string novoStatus = 2;</code>
     * @return The bytes for novoStatus.
     */
    public com.google.protobuf.ByteString
        getNovoStatusBytes() {
      java.lang.Object ref = novoStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        novoStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string novoStatus = 2;</code>
     * @param value The novoStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNovoStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      novoStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string novoStatus = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNovoStatus() {
      novoStatus_ = getDefaultInstance().getNovoStatus();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string novoStatus = 2;</code>
     * @param value The bytes for novoStatus to set.
     * @return This builder for chaining.
     */
    public Builder setNovoStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      novoStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:javafx.agendamento.AtualizarStatusAgendamentoRequest)
  }

  // @@protoc_insertion_point(class_scope:javafx.agendamento.AtualizarStatusAgendamentoRequest)
  private static final javafx.agendamento.AtualizarStatusAgendamentoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafx.agendamento.AtualizarStatusAgendamentoRequest();
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AtualizarStatusAgendamentoRequest>
      PARSER = new com.google.protobuf.AbstractParser<AtualizarStatusAgendamentoRequest>() {
    @java.lang.Override
    public AtualizarStatusAgendamentoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AtualizarStatusAgendamentoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AtualizarStatusAgendamentoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public javafx.agendamento.AtualizarStatusAgendamentoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

