// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

/**
 * Protobuf type {@code javafx.agendamento.AtualizarStatusAgendamentoResponse}
 */
public final class AtualizarStatusAgendamentoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:javafx.agendamento.AtualizarStatusAgendamentoResponse)
    AtualizarStatusAgendamentoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AtualizarStatusAgendamentoResponse.newBuilder() to construct.
  private AtualizarStatusAgendamentoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AtualizarStatusAgendamentoResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AtualizarStatusAgendamentoResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafx.agendamento.AtualizarStatusAgendamentoResponse.class, javafx.agendamento.AtualizarStatusAgendamentoResponse.Builder.class);
  }

  public static final int SUCESSO_FIELD_NUMBER = 1;
  private boolean sucesso_ = false;
  /**
   * <code>bool sucesso = 1;</code>
   * @return The sucesso.
   */
  @java.lang.Override
  public boolean getSucesso() {
    return sucesso_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sucesso_ != false) {
      output.writeBool(1, sucesso_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sucesso_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, sucesso_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafx.agendamento.AtualizarStatusAgendamentoResponse)) {
      return super.equals(obj);
    }
    javafx.agendamento.AtualizarStatusAgendamentoResponse other = (javafx.agendamento.AtualizarStatusAgendamentoResponse) obj;

    if (getSucesso()
        != other.getSucesso()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCESSO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSucesso());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.AtualizarStatusAgendamentoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafx.agendamento.AtualizarStatusAgendamentoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code javafx.agendamento.AtualizarStatusAgendamentoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:javafx.agendamento.AtualizarStatusAgendamentoResponse)
      javafx.agendamento.AtualizarStatusAgendamentoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafx.agendamento.AtualizarStatusAgendamentoResponse.class, javafx.agendamento.AtualizarStatusAgendamentoResponse.Builder.class);
    }

    // Construct using javafx.agendamento.AtualizarStatusAgendamentoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sucesso_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_AtualizarStatusAgendamentoResponse_descriptor;
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoResponse getDefaultInstanceForType() {
      return javafx.agendamento.AtualizarStatusAgendamentoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoResponse build() {
      javafx.agendamento.AtualizarStatusAgendamentoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public javafx.agendamento.AtualizarStatusAgendamentoResponse buildPartial() {
      javafx.agendamento.AtualizarStatusAgendamentoResponse result = new javafx.agendamento.AtualizarStatusAgendamentoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(javafx.agendamento.AtualizarStatusAgendamentoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sucesso_ = sucesso_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafx.agendamento.AtualizarStatusAgendamentoResponse) {
        return mergeFrom((javafx.agendamento.AtualizarStatusAgendamentoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafx.agendamento.AtualizarStatusAgendamentoResponse other) {
      if (other == javafx.agendamento.AtualizarStatusAgendamentoResponse.getDefaultInstance()) return this;
      if (other.getSucesso() != false) {
        setSucesso(other.getSucesso());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sucesso_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean sucesso_ ;
    /**
     * <code>bool sucesso = 1;</code>
     * @return The sucesso.
     */
    @java.lang.Override
    public boolean getSucesso() {
      return sucesso_;
    }
    /**
     * <code>bool sucesso = 1;</code>
     * @param value The sucesso to set.
     * @return This builder for chaining.
     */
    public Builder setSucesso(boolean value) {

      sucesso_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool sucesso = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSucesso() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sucesso_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:javafx.agendamento.AtualizarStatusAgendamentoResponse)
  }

  // @@protoc_insertion_point(class_scope:javafx.agendamento.AtualizarStatusAgendamentoResponse)
  private static final javafx.agendamento.AtualizarStatusAgendamentoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafx.agendamento.AtualizarStatusAgendamentoResponse();
  }

  public static javafx.agendamento.AtualizarStatusAgendamentoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AtualizarStatusAgendamentoResponse>
      PARSER = new com.google.protobuf.AbstractParser<AtualizarStatusAgendamentoResponse>() {
    @java.lang.Override
    public AtualizarStatusAgendamentoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AtualizarStatusAgendamentoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AtualizarStatusAgendamentoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public javafx.agendamento.AtualizarStatusAgendamentoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

