// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public interface GetAgendamentosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javafx.agendamento.GetAgendamentosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  java.util.List<javafx.agendamento.Agendamento> 
      getAgendamentosList();
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  javafx.agendamento.Agendamento getAgendamentos(int index);
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  int getAgendamentosCount();
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  java.util.List<? extends javafx.agendamento.AgendamentoOrBuilder> 
      getAgendamentosOrBuilderList();
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  javafx.agendamento.AgendamentoOrBuilder getAgendamentosOrBuilder(
      int index);
}
