// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

public interface GetAgendamentosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:javafx.agendamento.GetAgendamentosRequest)
    com.google.protobuf.MessageOrBuilder {
}
