// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agenda.proto

// Protobuf Java Version: 3.25.1
package javafx.agendamento;

/**
 * Protobuf type {@code javafx.agendamento.GetAgendamentosResponse}
 */
public final class GetAgendamentosResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:javafx.agendamento.GetAgendamentosResponse)
    GetAgendamentosResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAgendamentosResponse.newBuilder() to construct.
  private GetAgendamentosResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAgendamentosResponse() {
    agendamentos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAgendamentosResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_GetAgendamentosResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafx.agendamento.GetAgendamentosResponse.class, javafx.agendamento.GetAgendamentosResponse.Builder.class);
  }

  public static final int AGENDAMENTOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<javafx.agendamento.Agendamento> agendamentos_;
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<javafx.agendamento.Agendamento> getAgendamentosList() {
    return agendamentos_;
  }
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends javafx.agendamento.AgendamentoOrBuilder> 
      getAgendamentosOrBuilderList() {
    return agendamentos_;
  }
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  @java.lang.Override
  public int getAgendamentosCount() {
    return agendamentos_.size();
  }
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  @java.lang.Override
  public javafx.agendamento.Agendamento getAgendamentos(int index) {
    return agendamentos_.get(index);
  }
  /**
   * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
   */
  @java.lang.Override
  public javafx.agendamento.AgendamentoOrBuilder getAgendamentosOrBuilder(
      int index) {
    return agendamentos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < agendamentos_.size(); i++) {
      output.writeMessage(1, agendamentos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < agendamentos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, agendamentos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafx.agendamento.GetAgendamentosResponse)) {
      return super.equals(obj);
    }
    javafx.agendamento.GetAgendamentosResponse other = (javafx.agendamento.GetAgendamentosResponse) obj;

    if (!getAgendamentosList()
        .equals(other.getAgendamentosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAgendamentosCount() > 0) {
      hash = (37 * hash) + AGENDAMENTOS_FIELD_NUMBER;
      hash = (53 * hash) + getAgendamentosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static javafx.agendamento.GetAgendamentosResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static javafx.agendamento.GetAgendamentosResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafx.agendamento.GetAgendamentosResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafx.agendamento.GetAgendamentosResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code javafx.agendamento.GetAgendamentosResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:javafx.agendamento.GetAgendamentosResponse)
      javafx.agendamento.GetAgendamentosResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_GetAgendamentosResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafx.agendamento.GetAgendamentosResponse.class, javafx.agendamento.GetAgendamentosResponse.Builder.class);
    }

    // Construct using javafx.agendamento.GetAgendamentosResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (agendamentosBuilder_ == null) {
        agendamentos_ = java.util.Collections.emptyList();
      } else {
        agendamentos_ = null;
        agendamentosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafx.agendamento.AgendaProto.internal_static_javafx_agendamento_GetAgendamentosResponse_descriptor;
    }

    @java.lang.Override
    public javafx.agendamento.GetAgendamentosResponse getDefaultInstanceForType() {
      return javafx.agendamento.GetAgendamentosResponse.getDefaultInstance();
    }

    @java.lang.Override
    public javafx.agendamento.GetAgendamentosResponse build() {
      javafx.agendamento.GetAgendamentosResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public javafx.agendamento.GetAgendamentosResponse buildPartial() {
      javafx.agendamento.GetAgendamentosResponse result = new javafx.agendamento.GetAgendamentosResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(javafx.agendamento.GetAgendamentosResponse result) {
      if (agendamentosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          agendamentos_ = java.util.Collections.unmodifiableList(agendamentos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.agendamentos_ = agendamentos_;
      } else {
        result.agendamentos_ = agendamentosBuilder_.build();
      }
    }

    private void buildPartial0(javafx.agendamento.GetAgendamentosResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafx.agendamento.GetAgendamentosResponse) {
        return mergeFrom((javafx.agendamento.GetAgendamentosResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafx.agendamento.GetAgendamentosResponse other) {
      if (other == javafx.agendamento.GetAgendamentosResponse.getDefaultInstance()) return this;
      if (agendamentosBuilder_ == null) {
        if (!other.agendamentos_.isEmpty()) {
          if (agendamentos_.isEmpty()) {
            agendamentos_ = other.agendamentos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAgendamentosIsMutable();
            agendamentos_.addAll(other.agendamentos_);
          }
          onChanged();
        }
      } else {
        if (!other.agendamentos_.isEmpty()) {
          if (agendamentosBuilder_.isEmpty()) {
            agendamentosBuilder_.dispose();
            agendamentosBuilder_ = null;
            agendamentos_ = other.agendamentos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            agendamentosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAgendamentosFieldBuilder() : null;
          } else {
            agendamentosBuilder_.addAllMessages(other.agendamentos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              javafx.agendamento.Agendamento m =
                  input.readMessage(
                      javafx.agendamento.Agendamento.parser(),
                      extensionRegistry);
              if (agendamentosBuilder_ == null) {
                ensureAgendamentosIsMutable();
                agendamentos_.add(m);
              } else {
                agendamentosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<javafx.agendamento.Agendamento> agendamentos_ =
      java.util.Collections.emptyList();
    private void ensureAgendamentosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        agendamentos_ = new java.util.ArrayList<javafx.agendamento.Agendamento>(agendamentos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        javafx.agendamento.Agendamento, javafx.agendamento.Agendamento.Builder, javafx.agendamento.AgendamentoOrBuilder> agendamentosBuilder_;

    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public java.util.List<javafx.agendamento.Agendamento> getAgendamentosList() {
      if (agendamentosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(agendamentos_);
      } else {
        return agendamentosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public int getAgendamentosCount() {
      if (agendamentosBuilder_ == null) {
        return agendamentos_.size();
      } else {
        return agendamentosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public javafx.agendamento.Agendamento getAgendamentos(int index) {
      if (agendamentosBuilder_ == null) {
        return agendamentos_.get(index);
      } else {
        return agendamentosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder setAgendamentos(
        int index, javafx.agendamento.Agendamento value) {
      if (agendamentosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgendamentosIsMutable();
        agendamentos_.set(index, value);
        onChanged();
      } else {
        agendamentosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder setAgendamentos(
        int index, javafx.agendamento.Agendamento.Builder builderForValue) {
      if (agendamentosBuilder_ == null) {
        ensureAgendamentosIsMutable();
        agendamentos_.set(index, builderForValue.build());
        onChanged();
      } else {
        agendamentosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder addAgendamentos(javafx.agendamento.Agendamento value) {
      if (agendamentosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgendamentosIsMutable();
        agendamentos_.add(value);
        onChanged();
      } else {
        agendamentosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder addAgendamentos(
        int index, javafx.agendamento.Agendamento value) {
      if (agendamentosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAgendamentosIsMutable();
        agendamentos_.add(index, value);
        onChanged();
      } else {
        agendamentosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder addAgendamentos(
        javafx.agendamento.Agendamento.Builder builderForValue) {
      if (agendamentosBuilder_ == null) {
        ensureAgendamentosIsMutable();
        agendamentos_.add(builderForValue.build());
        onChanged();
      } else {
        agendamentosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder addAgendamentos(
        int index, javafx.agendamento.Agendamento.Builder builderForValue) {
      if (agendamentosBuilder_ == null) {
        ensureAgendamentosIsMutable();
        agendamentos_.add(index, builderForValue.build());
        onChanged();
      } else {
        agendamentosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder addAllAgendamentos(
        java.lang.Iterable<? extends javafx.agendamento.Agendamento> values) {
      if (agendamentosBuilder_ == null) {
        ensureAgendamentosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, agendamentos_);
        onChanged();
      } else {
        agendamentosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder clearAgendamentos() {
      if (agendamentosBuilder_ == null) {
        agendamentos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        agendamentosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public Builder removeAgendamentos(int index) {
      if (agendamentosBuilder_ == null) {
        ensureAgendamentosIsMutable();
        agendamentos_.remove(index);
        onChanged();
      } else {
        agendamentosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public javafx.agendamento.Agendamento.Builder getAgendamentosBuilder(
        int index) {
      return getAgendamentosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public javafx.agendamento.AgendamentoOrBuilder getAgendamentosOrBuilder(
        int index) {
      if (agendamentosBuilder_ == null) {
        return agendamentos_.get(index);  } else {
        return agendamentosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public java.util.List<? extends javafx.agendamento.AgendamentoOrBuilder> 
         getAgendamentosOrBuilderList() {
      if (agendamentosBuilder_ != null) {
        return agendamentosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(agendamentos_);
      }
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public javafx.agendamento.Agendamento.Builder addAgendamentosBuilder() {
      return getAgendamentosFieldBuilder().addBuilder(
          javafx.agendamento.Agendamento.getDefaultInstance());
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public javafx.agendamento.Agendamento.Builder addAgendamentosBuilder(
        int index) {
      return getAgendamentosFieldBuilder().addBuilder(
          index, javafx.agendamento.Agendamento.getDefaultInstance());
    }
    /**
     * <code>repeated .javafx.agendamento.Agendamento agendamentos = 1;</code>
     */
    public java.util.List<javafx.agendamento.Agendamento.Builder> 
         getAgendamentosBuilderList() {
      return getAgendamentosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        javafx.agendamento.Agendamento, javafx.agendamento.Agendamento.Builder, javafx.agendamento.AgendamentoOrBuilder> 
        getAgendamentosFieldBuilder() {
      if (agendamentosBuilder_ == null) {
        agendamentosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            javafx.agendamento.Agendamento, javafx.agendamento.Agendamento.Builder, javafx.agendamento.AgendamentoOrBuilder>(
                agendamentos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        agendamentos_ = null;
      }
      return agendamentosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:javafx.agendamento.GetAgendamentosResponse)
  }

  // @@protoc_insertion_point(class_scope:javafx.agendamento.GetAgendamentosResponse)
  private static final javafx.agendamento.GetAgendamentosResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafx.agendamento.GetAgendamentosResponse();
  }

  public static javafx.agendamento.GetAgendamentosResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAgendamentosResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAgendamentosResponse>() {
    @java.lang.Override
    public GetAgendamentosResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAgendamentosResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAgendamentosResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public javafx.agendamento.GetAgendamentosResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

